// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2jaHSB9XauiPcz_TiywvFwH_1DnTSkAo',
    appId: '1:936691562566:web:e857d5614b0fc6d0493247',
    messagingSenderId: '936691562566',
    projectId: 'twitter-flutter-clone-new',
    authDomain: 'twitter-flutter-clone-new.firebaseapp.com',
    storageBucket: 'twitter-flutter-clone-new.appspot.com',
    measurementId: 'G-9RSJYX3JCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2mU5ewEBfqctzilC0fM1djeKcp862rlw',
    appId: '1:936691562566:android:c89a6b70ae64c18a493247',
    messagingSenderId: '936691562566',
    projectId: 'twitter-flutter-clone-new',
    storageBucket: 'twitter-flutter-clone-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATKJ_miVkmdOlO9p2bCNAavvSK_j_mRrg',
    appId: '1:936691562566:ios:913ddf1e99569bb4493247',
    messagingSenderId: '936691562566',
    projectId: 'twitter-flutter-clone-new',
    storageBucket: 'twitter-flutter-clone-new.appspot.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATKJ_miVkmdOlO9p2bCNAavvSK_j_mRrg',
    appId: '1:936691562566:ios:63a2f591e00b5343493247',
    messagingSenderId: '936691562566',
    projectId: 'twitter-flutter-clone-new',
    storageBucket: 'twitter-flutter-clone-new.appspot.com',
    iosBundleId: 'com.example.twitterClone.RunnerTests',
  );
}
